Feat/project name variable
elarivie/linter-mypy pull request #3
Opened 2017-03-12 21:34 UTC by tebanep

This pull request enables the usage of a $PROJECT_NAME variable in the Executable Path option.

With this, the mypy executable of different virtual environments can be used with a single configuration by following the convention of locating all virtual environments in the same directory (e.g. ~/.virtualenvironments) and name them after each project's name.

2017-03-12 22:22 UTC, tebanep commented
This solves issue #2

2017-03-13 02:35 UTC, elarivie requested changes
Good job

But please adjust your pull request base on the code review comments

2017-03-13 02:35 UTC, elarivie commented on lib/init.coffee
> +      projectPath = projectPaths[0]
Should not randomly pick the project path at index 0

Should loop over all possible project path and find out which project actually contains the current file being linted (see above comment the file path being linted should be provided as a parameter)

2017-03-13 02:35 UTC, elarivie commented on lib/init.coffee
> +        @executablePath = @resolvePath executablePath
The resolvePath call should not be done immediately after the setting has change/loaded

What if at the time the setting is changed by the user there are more than one project open?, what if no project is open?
I am pretty sure in those scenarios the @executablePath will hold an invalid path which won't change till the user manually edit the setting.

The call to resolve the executable path should instead be done at the last minute [Line 249 where the actual call to python is done](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L249).

Also the resolving of the path should be done every time a call to python has to be done and therefore when resolving the executable path it should not store permanently the computed result, it should use it to make the call to python and forget about it since the resolved path may be different for the next file to lint.

**Note:** the resolved path should be use to make the call to python: 
- [Line 249](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L249)

**AND** to be shown in the different pop-up message in case something goes wrong:
- [Line 293](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L293)
- [Line 324](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L324)
- [Line 350](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L350)

2017-03-13 02:35 UTC, elarivie commented on lib/init.coffee
> +  resolvePath: (targetPath) ->
This method should also need the path to the file being linted, with this path we can then find out which project it belongs to

Parameter#1 = The executable path as provided by the setting
Parameter#2 = The file path of the file being linted

2017-03-13 02:35 UTC, elarivie commented on spec/linter-mypy_project_name-spec.coffee
> +fdescribe "The MyPy provider for Linter", ->
fdescribe vs describe

There is an extra f at the beginning of the line... is it needed?

2017-03-13 14:17 UTC, tebanep commented on lib/init.coffee
> +        @executablePath = @resolvePath executablePath
Perfect @elarivie, I will make those changes. :)

2017-03-13 17:16 UTC, tebanep commented
Now i use the current file for resolvePath(). This way, the method works with multiple project roots.

2017-03-13 17:46 UTC, Arcanemagus requested changes

2017-03-13 17:46 UTC, Arcanemagus commented on lib/init.coffee
> +    projectName = path.parse(projectPath).name
`projectPath` can be `null` if the requested `filepath` is not part of an open Atom project (the file was opened on its own). You should be checking for that before attempting to `path.parse` it.

2017-03-13 18:28 UTC, tebanep commented on lib/init.coffee
> +    projectName = path.parse(projectPath).name
Ok :)

2017-03-14 02:30 UTC, merged